export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

export const UPDATE_USERINFO = 'UPDATE_USERINFO'

export const REFRESH_CHANNELS = 'REFRESH_CHANNELS'
export const ADD_PM_CHANNEL = 'ADD_PM_CHANNEL'
export const CLEAR_CHANNELS = 'CLEAR_CHANNELS'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const PREPEND_MESSAGE = 'PREPEND_MESSAGE'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'

export const INIT_POS = 'INIT_POS'
export const UPDATE_POS = 'UPDATE_POS'
export const UPDATE_POS_SPECIFIC = 'UPDATE_POS_SPECIFIC'

export const ADD_USER = 'ADD_USER'
export const ADD_USERS = 'ADD_USERS'
